"""
Discovery-priors index: parse the validated cross-run knowledge base and select
the FEW findings relevant to a generation's dominant failure mode, so they can be
INLINED into the failure report (Layer 1 of the priors overhaul).

Why inline instead of "go read the file":
  The old flow only POINTED the reviser at ``all-runs.combined.md`` and hoped it
  opened it (``read_priors`` was often False -> "un-grounded improvement"). Making
  the grounding a section of the report the reviser already reads removes the
  "didn't read" failure mode entirely, and matching to THIS generation's failure
  mode keeps the signal focused instead of "survey all 24 findings yourself".

Trust discipline (mirrors ``run_evolution._format_priors``): a finding QUALIFIES
only if its Generalization is GENERALIZES and its verdict is NOT in the distrust
set (DOES-NOT-GENERALIZE / PARTIAL / WEAKENED / OVERTURNED). These are GT-derived
POPULATION statistics about error geometry, never this run's labels, so using
their thresholds/discriminators does not violate the no-hardcoded-label rule.

The parser is deliberately tolerant: the knowledge base is regenerated by the
AutoDiscovery consolidation workflow, so we key on the stable structure (``### N.
(Priority …) title`` headers + a ``**Verdict carried over:**`` line) and degrade to
"no priors section" rather than ever raising into the evolution loop.
"""

from __future__ import annotations

import re


# A finding is DISTRUSTED (never inlined) if its verdict line carries any of these
# — the same list run_evolution._format_priors tells the reviser to avoid.
_DISTRUST = ("DOES-NOT-GENERALIZE", "PARTIAL", "WEAKENED", "OVERTURNED")

_HEADER_RE = re.compile(r"^###\s+(\d+)\.\s*\(([^)]*)\)\s*(.+?)\s*$")
_PRIORITY_RE = re.compile(r"Priority\s+([0-9.]+)")

# Keyword sets that tag a finding by which failure mode it informs. A finding may
# carry BOTH (e.g. a proximity classifier bounds recall AND precision). Matched
# against the finding title (lowercased) — robust to the file being renumbered.
_PRECISION_KW = (
    "angle", "angular", "collinear", "colinear", "anti-parallel", "cosine",
    "inertia", "continuation", "crossing", "radius", "caliber", "tortuosity",
    "asymmetric", "overlap", "runaway", "giant",
)
_RECALL_KW = (
    "threshold", "proximity", "gap", "reconnect", "search radius", "bimodal",
    "distance", "branch point", "branch", "distal", "terminal", "micro-fragment",
    "tiny", "small",
)


class Finding:
    """One parsed knowledge-base finding (see module docstring for the fields)."""

    __slots__ = ("num", "title", "priority", "verdict_line", "conclusion", "tags",
                 "text")

    def __init__(self, num, title, priority, verdict_line, conclusion, tags, text=""):
        self.num = num
        self.title = title
        self.priority = priority
        self.verdict_line = verdict_line
        self.conclusion = conclusion
        self.tags = tags
        # Lowercased title + conclusion — the corpus for CONTENT matching against a
        # generation's failure signature (see relevance()). Matching the whole text,
        # not just the title, is what lets the KB be re-titled / reworded without
        # silently losing a finding's routing (the old title-keyword weakness).
        self.text = text

    @property
    def qualifies(self) -> bool:
        """GENERALIZES and not in the distrust set (see module docstring)."""
        vl = self.verdict_line or ""
        if "GENERALIZES" not in vl:            # note: 'DOES-NOT-GENERALIZE' lacks the S
            return False
        return not any(bad in vl for bad in _DISTRUST)


def _tags_for(title: str) -> set:
    """Coarse precision/recall tags from the title (kept as ONE weak signal for
    relevance(); no longer the sole router — content overlap dominates)."""
    t = title.lower()
    tags = set()
    if any(k in t for k in _PRECISION_KW):
        tags.add("precision")
    if any(k in t for k in _RECALL_KW):
        tags.add("recall")
    return tags


# Vocabulary that describes each failure mode's GEOMETRY, used to score a finding's
# CONTENT (title + conclusion) against the current failure — a graded overlap, not a
# title-keyword gate. Broader than the tag keywords on purpose: relevance is a score,
# so extra terms help rank rather than mis-route.
_MODE_VOCAB = {
    "precision": ("angle", "angular", "crossing", "collinear", "colinear", "parallel",
                  "cosine", "continuation", "radius", "caliber", "ratio", "overlap",
                  "asymmetric", "tortuosity", "inertia", "runaway", "giant",
                  "false merge", "over-merge", "precision", "distinct", "different"),
    "recall": ("threshold", "proximity", "gap", "distance", "reconnect", "search",
               "bimodal", "branch", "distal", "terminal", "micro", "tiny", "small",
               "split", "missed", "recall", "dropout", "reach"),
}


def _tokenize(s: str) -> set:
    return set(re.findall(r"[a-z][a-z\-]{2,}", (s or "").lower()))


def relevance(f: "Finding", failure_mode: str, signature=None) -> float:
    """Graded relevance of a finding to THIS generation's failure — CONTENT-based.

    Combines three signals (all in [0,1]-ish, summed) instead of a title-keyword gate:
      * mode-vocabulary overlap: how much the finding's TEXT talks about the geometry
        of the dominant failure mode (precision vs recall vocab);
      * signature overlap: tokens shared with a free-form ``signature`` string built
        from the actual failure report (e.g. dominant feature axes), when provided;
      * a small tag bonus (the old precision/recall tag) and a tiny Priority nudge as
        a tie-breaker — Priority ranks discovery importance, so it only breaks ties.
    Higher = more relevant. Never raises; unknown mode falls back to both vocabs.
    """
    text_tokens = _tokenize(f.text or f.title)
    vocab = set()
    if failure_mode in _MODE_VOCAB:
        vocab = set(_MODE_VOCAB[failure_mode])
    else:  # cold_start / both / unknown -> consider both geometries
        for v in _MODE_VOCAB.values():
            vocab |= set(v)
    # Count vocab hits as substrings of the finding text (so multi-word phrases like
    # "false merge" match), normalized by vocab size.
    ftext = (f.text or f.title or "")
    vocab_hits = sum(1 for kw in vocab if kw in ftext)
    vocab_score = vocab_hits / max(1, len(vocab)) * 4.0   # weight up (dominant signal)

    sig_score = 0.0
    if signature:
        sig_tokens = _tokenize(signature)
        if sig_tokens:
            overlap = len(text_tokens & sig_tokens)
            sig_score = overlap / max(1, len(sig_tokens)) * 3.0

    want = {"precision": {"precision"}, "recall": {"recall"}}.get(
        failure_mode, {"precision", "recall"})
    tag_bonus = 0.5 if (f.tags & want) else 0.0
    priority_nudge = min(max(f.priority, 0.0), 1.0) * 0.1   # tie-breaker only
    return vocab_score + sig_score + tag_bonus + priority_nudge


def load_findings(priors_path: str) -> list:
    """Parse the knowledge base into ``Finding`` objects. Returns [] on any problem
    (missing/garbled file) so the caller can proceed without a priors section."""
    try:
        with open(priors_path) as f:
            text = f.read()
    except OSError:
        return []

    findings: list = []
    cur = None          # (num, title, priority)
    body: list = []

    def _flush():
        if cur is None:
            return
        num, title, priority = cur
        blob = "\n".join(body)
        verdict_line = ""
        conclusion = ""
        for ln in body:
            s = ln.strip()
            if s.startswith("- **Verdict carried over:") or s.startswith("**Verdict carried over:"):
                verdict_line = s
            elif (not conclusion) and ("**Conclusion" in s):
                # Text after the 'Conclusion' marker; strip the markdown '**' and any
                # leading colon/space so the snippet starts at the real sentence.
                after = s.split("Conclusion", 1)[1]
                after = after.split(":", 1)[1] if ":" in after else after
                conclusion = after.lstrip("* )").strip()
        findings.append(Finding(num, title, priority, verdict_line,
                                 conclusion, _tags_for(title),
                                 text=f"{title}. {conclusion}".lower()))

    for line in text.splitlines():
        m = _HEADER_RE.match(line)
        if m:
            _flush()
            num = int(m.group(1))
            meta, title = m.group(2), m.group(3)
            pm = _PRIORITY_RE.search(meta)
            priority = float(pm.group(1)) if pm else 0.0
            cur = (num, title, priority)
            body = []
        elif cur is not None:
            body.append(line)
    _flush()
    return findings


def select_for_report(findings: list, failure_mode: str, k: int = 2,
                       signature=None, failed_findings=None, shown_counts=None) -> list:
    """Pick up to ``k`` QUALIFYING findings for THIS generation — content-matched,
    with the harness feedback loop CLOSED (not just displayed).

    Ranking (highest first), all deterministic:
      1. CONTENT relevance to the current failure (``relevance`` over the finding's
         full text + an optional ``signature`` string built from the actual failure
         report), replacing the old title-keyword-only gate (fix #3).
      2. Penalize findings already CITED in a generation that was then REVERTED
         (``failed_findings``): a lever that was tried against the current lineage and
         did not beat the parent should not be re-offered first (fix #2). It is
         down-weighted, not hard-excluded, so it can still resurface if nothing else
         qualifies and the failure mode shifts.
      3. ROTATE by exposure: findings surfaced many times already (``shown_counts``)
         are nudged down so the reviser eventually sees the whole qualifying set
         rather than the same two every generation (fix #2).

    ``failed_findings`` : set[int] of finding numbers cited in a reverted gen.
    ``shown_counts``    : dict[int,int] of how many times each finding was surfaced.
    Both default empty (first generation / feedback disabled) → pure content ranking.
    """
    q = [f for f in findings if f.qualifies]
    if not q:
        return []
    failed = set(failed_findings or ())
    shown = dict(shown_counts or {})

    def _key(f):
        score = relevance(f, failure_mode, signature)
        if f.num in failed:
            score -= 2.0                      # tried-and-reverted: strong down-weight
        score -= 0.5 * shown.get(f.num, 0)    # rotation: fade with repeated exposure
        # Tie-break deterministically by finding number so the order is stable.
        return (score, -f.num)

    q.sort(key=_key, reverse=True)
    return q[:k]


_NUM_RE = re.compile(r"\d")


def _snippet(f: Finding, n: int = 480) -> str:
    """The threshold/discriminator text the reviser can key a rule on.

    A rule needs the OPERATIVE NUMBER (e.g. "6.84 µm threshold", "angle > 45°",
    "radius ratio ~1.0"), and in this KB that number is usually NOT in the first
    sentence — the opener is often setup ("Tested whether …"). So instead of the old
    first-sentence-only cut (which dropped the number), keep the sentences that carry
    a DIGIT (the thresholds/discriminators), always including the first for context,
    up to ``n`` chars. Falls back to the leading text if nothing is numeric.
    """
    c = (f.conclusion or "").strip()
    if not c:
        return ""
    # Split into sentences on ". " (keep it simple; the KB is prose).
    import re as _re
    sents = [s.strip() for s in _re.split(r"(?<=[.;])\s+", c) if s.strip()]
    if not sents:
        return c[:n]
    kept, seen = [], set()
    # Always include the first sentence (context), then every number-bearing one.
    for i, s in enumerate(sents):
        if i == 0 or _NUM_RE.search(s):
            if s not in seen:
                kept.append(s); seen.add(s)
        if sum(len(x) + 1 for x in kept) >= n:
            break
    out = " ".join(kept).strip()
    return out[:n] if len(out) > n else out


def render_section(selected: list, failure_mode: str) -> list:
    """Render the inlined 'grounding priors' block as a list of markdown lines.

    Returns [] when nothing qualified/matched. The block is written ONCE at the top
    of the failure report (it is a cross-brain generality, not per-brain), and each
    finding names WHICH report section it informs so the reviser can act on it in
    place instead of hunting through the full knowledge base.
    """
    if not selected:
        return []
    mode_h = {"precision": "OVER-MERGING (you created false merges — tighten)",
              "recall": "UNDER-REPAIR (correct merges, but splits left unrepaired — "
                        "raise recall)",
              "cold_start": "COLD START (policy is not merging yet — start repairing "
                            "the safest splits)"}.get(failure_mode,
                            "MIXED (precision and recall both in play)")
    lines = [
        "\n## Grounding priors (validated cross-brain — matched to THIS failure mode)\n",
        f"Dominant failure mode this generation: **{mode_h}**. The findings below are "
        f"from the AutoDiscovery knowledge base and are pre-filtered to those that "
        f"GENERALIZE across every brain AND survive statistical correction, then "
        f"matched to that mode. They are GT-derived POPULATION geometry (not this "
        f"run's labels), so keying a threshold/discriminator on them is fair game and "
        f"does NOT violate the no-hardcoded-label rule. They only BIAS your proposal — "
        f"the held-out gate still decides. Cite the finding number in your rules.md "
        f"change log so we can measure whether grounding helps.\n",
    ]
    for f in selected:
        which = ("the SplitSite audit's 'WRONGLY accepted false joins' bucket"
                 if failure_mode == "precision"
                 else "the SplitSite audit's 'MISSED real splits' bucket")
        lines.append(
            f"- **Finding #{f.num} — {f.title}**\n"
            f"  - Threshold/discriminator: {_snippet(f)}\n"
            f"  - Use it against: {which}.\n"
        )
    lines.append(
        "\nThese are the MATCHED few; the full knowledge base has more levers if none "
        "of the above fits — prefer a lever you and prior generations have not tried "
        "yet.\n"
    )
    return lines


def build_report_section(priors_path: str, failure_mode: str, k: int = 2,
                         signature=None, failed_findings=None, shown_counts=None):
    """Convenience: load + select + render in one call.

    Returns ``(lines, shown_nums)`` where ``lines`` is the markdown block (``[]`` on
    any failure, so the report builder can splice unconditionally) and ``shown_nums``
    is the list of finding numbers actually surfaced this generation — the caller
    uses it to update ``shown_counts`` (rotation) for the next call. The extra args
    thread the CLOSED feedback loop (signature = content match; failed_findings =
    down-weight tried-and-reverted; shown_counts = rotation)."""
    try:
        findings = load_findings(priors_path)
        selected = select_for_report(findings, failure_mode, k, signature=signature,
                                     failed_findings=failed_findings,
                                     shown_counts=shown_counts)
        return render_section(selected, failure_mode), [f.num for f in selected]
    except Exception:
        return [], []


# A rules.md change-log citation of a finding, e.g. "Finding #8", "finding 8",
# "#8". We require the explicit '#'/'finding' form so a bare number in prose (a µm
# threshold, a count) is not a citation. We deliberately do NOT match a bare "F8"/
# "F1": "F1" collides with the F1-score wording that appears in the priors text
# itself (finding #1's "F1 = 0.9945"), which would be a false positive if echoed.
_CITE_RE = re.compile(r"(?:finding\s*#?\s*|#)(\d{1,3})\b", re.IGNORECASE)


def cited_findings(change_log_text: str) -> set:
    """Return the set of finding numbers the reviser cited in text it wrote.

    Layer-2 'grounded' detection: the prompt already asks the reviser to cite the
    finding number(s) it relied on in the rules.md change log. A citation means the
    prior MAY have shaped the edit — but citing is not the same as USING (see
    ``supported_citations`` for the stronger check). Used to tag the generation
    grounded vs exploratory so we can measure whether grounding generalizes better.
    """
    if not change_log_text:
        return set()
    return {int(m.group(1)) for m in _CITE_RE.finditer(change_log_text)}


# Domain stop-words: tokens too generic to prove a finding was actually USED (they
# appear in almost every finding + almost every rule change). A citation is only
# "supported" if the added text shares CONTENTFUL vocabulary with the finding beyond
# these — so "I applied finding #1" with no matching geometry term is NOT supported.
_GENERIC_TOKENS = frozenset((
    "the", "and", "for", "with", "this", "that", "split", "merge", "merges", "splits",
    "neuron", "neurons", "fragment", "fragments", "gap", "edit", "edits", "policy",
    "rule", "rules", "finding", "change", "threshold", "add", "added", "use", "using",
))


def supported_citations(change_log_text: str, added_code_text: str,
                        findings: list) -> set:
    """Subset of cited findings whose CONTENT actually shows up in what the reviser
    changed — a stronger 'grounded' signal than a bare ``#N`` citation.

    A citation of finding N is SUPPORTED when the reviser's added text (rules change
    log + the added heuristics.py lines) shares at least one CONTENTFUL token with
    finding N's own text (title + conclusion), excluding generic domain stop-words.
    This distinguishes "cited AND the edit reflects the finding's geometry" from
    "typed #N but changed something unrelated" — closing the gap the reviewer flagged
    (citing ≠ using). Conservative by construction: it can miss a genuine use that
    shares no vocabulary, so it is reported ALONGSIDE the raw citation, not instead of
    it (the harness records both; the payoff analysis can use the stronger one).
    """
    cited = cited_findings(change_log_text)
    if not cited or not findings:
        return set()
    by_num = {f.num: f for f in findings}
    added_tokens = _tokenize(f"{change_log_text}\n{added_code_text or ''}") - _GENERIC_TOKENS
    supported = set()
    for n in cited:
        f = by_num.get(n)
        if f is None:
            continue
        ftoks = (_tokenize(f.text or f.title) - _GENERIC_TOKENS)
        if added_tokens & ftoks:
            supported.add(n)
    return supported
