"""
Discovery-priors index: parse the validated cross-run knowledge base and present
the QUALIFYING findings to a generation, RANKED by discovery importance × relevance
to the current failure, so they can be INLINED into the failure report (Layer 1 of
the priors overhaul).

DORMANT (as of the priors rewind): run_evolution.py no longer calls this module.
The evolution loop was rewound to the earlier design where the reviser is simply
POINTED at the knowledge base and READS it itself (see ``_format_priors`` there) —
the failure report inlines NO ranked menu, and there is no grounded/cited/rotation
feedback loop. Everything below describes the (now inactive) inline-menu pipeline;
it is retained intact so that path can be re-enabled by wiring ``build_report_section``
back into the loop, but NONE of it runs today. Read the rest of this docstring as
"what this module WOULD do if re-enabled", not as current behavior.

Why inline instead of "go read the file":
  The old flow only POINTED the reviser at ``all-runs.combined.md`` and hoped it
  opened it (``read_priors`` was often False -> "un-grounded improvement"). Making
  the grounding a section of the report the reviser already reads removes the
  "didn't read" failure mode entirely.

Menu, not a forced pick (design revision):
  An earlier version hard-selected the top-2 findings and HID their Priority, on the
  theory that naming a favoured few would anchor the agent. That proved too rigid: it
  starved the other qualifying levers and gave the agent no importance signal. Now we
  surface the WHOLE qualifying set as a ranked MENU — each finding shown WITH its
  Priority and threshold/discriminator — ordered by a weighted score that makes
  Priority a real co-driver (not a tie-breaker). The agent is free to read, pick, and
  COMBINE any of them; ranking guides the eye toward the high-importance, on-mode
  levers without removing the rest. This keeps the signal focused (it is still only
  the ~dozen findings that GENERALIZE, ranked to this failure) while restoring
  breadth and an explicit importance cue.

Trust discipline (mirrors ``run_evolution._format_priors``): a finding QUALIFIES
iff (a) its verdict line carries NO distrust marker (DOES-NOT-GENERALIZE / PARTIAL /
WEAKENED / OVERTURNED — the veto dominates) AND (b) it carries POSITIVE evidence that
it held up: a GENERALIZES, UPHELD, or SOUND token. Accepting UPHELD/SOUND — not just
the literal "GENERALIZES" — matches the "GENERALIZES + UPHELD/OK" rule the prompt
advertises and admits CONSOLIDATED findings whose clustered verdict line reads
"Verdict SOUND … Post-correction UPHELD" instead of "Generalization GENERALIZES".
These are GT-derived POPULATION statistics about error geometry, never this run's
labels, so using their thresholds/discriminators does not violate the
no-hardcoded-label rule.

The parser is deliberately tolerant: the knowledge base is regenerated by the
AutoDiscovery consolidation workflow, so we key on the stable structure (``### N.
(Priority …) title`` headers + a ``**Verdict carried over:**`` line) and degrade to
"no priors section" rather than ever raising into the evolution loop.
"""

from __future__ import annotations

import re


# A finding is DISTRUSTED (never inlined) if its verdict line carries any of these
# — the same list run_evolution._format_priors tells the reviser to avoid. This VETO
# always dominates: one generalization-failure marker anywhere in the (possibly
# clustered) verdict line sinks the finding, even if another sub-result held up.
_DISTRUST = ("DOES-NOT-GENERALIZE", "PARTIAL", "WEAKENED", "OVERTURNED")

# POSITIVE verdict evidence that a finding held up. The AutoDiscovery consolidation
# writes verdict lines in TWO shapes: single findings say "Generalization GENERALIZES
# (…)", while CONSOLIDATED/clustered ones carry only a "Verdict SOUND"/"Post-correction
# UPHELD" token and NO literal "GENERALIZES". The prompt (_format_priors) already
# advertises the trust rule as "GENERALIZES + UPHELD/OK", so accepting SOUND/UPHELD
# here aligns the code with what the reviser is told — and recovers strongly
# corroborated findings (e.g. merge-density, tiny-split-gaps) that the GENERALIZES-only
# check silently dropped on a wording technicality. Note 'GENERALIZES' carries the
# trailing S that 'DOES-NOT-GENERALIZE' lacks, so it never matches the distrust token.
_POSITIVE = ("GENERALIZES", "UPHELD", "SOUND")

_HEADER_RE = re.compile(r"^###\s+(\d+)\.\s*\(([^)]*)\)\s*(.+?)\s*$")
_PRIORITY_RE = re.compile(r"Priority\s+([0-9.]+)")

# Keyword sets that tag a finding by which failure mode it informs. A finding may
# carry BOTH (e.g. a proximity classifier bounds recall AND precision). Matched
# against the finding title (lowercased) — robust to the file being renumbered.
_PRECISION_KW = (
    "angle", "angular", "collinear", "colinear", "anti-parallel", "cosine",
    "inertia", "continuation", "crossing", "radius", "caliber", "tortuosity",
    "asymmetric", "overlap", "runaway", "giant",
)
_RECALL_KW = (
    "threshold", "proximity", "gap", "reconnect", "search radius", "bimodal",
    "distance", "branch point", "branch", "distal", "terminal", "micro-fragment",
    "tiny", "small",
)


class Finding:
    """One parsed knowledge-base finding (see module docstring for the fields)."""

    __slots__ = ("num", "title", "priority", "verdict_line", "conclusion", "tags",
                 "text")

    def __init__(self, num, title, priority, verdict_line, conclusion, tags, text=""):
        self.num = num
        self.title = title
        self.priority = priority
        self.verdict_line = verdict_line
        self.conclusion = conclusion
        self.tags = tags
        # Lowercased title + conclusion — the corpus for CONTENT matching against a
        # generation's failure signature (see relevance()). Matching the whole text,
        # not just the title, is what lets the KB be re-titled / reworded without
        # silently losing a finding's routing (the old title-keyword weakness).
        self.text = text

    @property
    def qualifies(self) -> bool:
        """Held up across brains AND after correction — safe to inline.

        Two conditions (see module docstring):
          1. DISTRUST VETO dominates — reject if the verdict line carries any
             DOES-NOT-GENERALIZE / PARTIAL / WEAKENED / OVERTURNED marker.
          2. POSITIVE evidence required — the line must carry a GENERALIZES, UPHELD, or
             SOUND token. Accepting UPHELD/SOUND (not just the literal GENERALIZES)
             matches the trust rule the prompt advertises and recovers clustered
             findings whose verdict line omits the GENERALIZES wording.
        """
        vl = self.verdict_line or ""
        if any(bad in vl for bad in _DISTRUST):   # note: 'DOES-NOT-GENERALIZE' lacks the S
            return False
        return any(good in vl for good in _POSITIVE)


def _tags_for(title: str) -> set:
    """Coarse precision/recall tags from the title (kept as ONE weak signal for
    relevance(); no longer the sole router — content overlap dominates)."""
    t = title.lower()
    tags = set()
    if any(k in t for k in _PRECISION_KW):
        tags.add("precision")
    if any(k in t for k in _RECALL_KW):
        tags.add("recall")
    return tags


# Vocabulary that describes each failure mode's GEOMETRY, used to score a finding's
# CONTENT (title + conclusion) against the current failure — a graded overlap, not a
# title-keyword gate. Broader than the tag keywords on purpose: relevance is a score,
# so extra terms help rank rather than mis-route.
_MODE_VOCAB = {
    "precision": ("angle", "angular", "crossing", "collinear", "colinear", "parallel",
                  "cosine", "continuation", "radius", "caliber", "ratio", "overlap",
                  "asymmetric", "tortuosity", "inertia", "runaway", "giant",
                  "false merge", "over-merge", "precision", "distinct", "different"),
    "recall": ("threshold", "proximity", "gap", "distance", "reconnect", "search",
               "bimodal", "branch", "distal", "terminal", "micro", "tiny", "small",
               "split", "missed", "recall", "dropout", "reach"),
}


def _tokenize(s: str) -> set:
    return set(re.findall(r"[a-z][a-z\-]{2,}", (s or "").lower()))


# How strongly discovery IMPORTANCE (a finding's Priority) co-drives the menu order,
# relative to content relevance. Priority is in [0,1]; relevance typically spans
# ~0–2.5. At 1.5 a top-priority finding gets a ~+1.5 boost — enough to out-rank a
# marginally-more-relevant but low-importance finding, without overriding a strong
# on-mode content match. This is the knob that turns "priority ~ignored" into
# "priority is a real co-driver" (the design revision). Raise to weight importance
# harder, lower to let relevance dominate again.
PRIORITY_WEIGHT = 1.5


def relevance(f: "Finding", failure_mode: str, signature=None) -> float:
    """Graded CONTENT relevance of a finding to THIS generation's failure.

    Combines two content signals (Priority is deliberately NOT here — it enters the
    menu order separately, see ``ranking_score``, so relevance stays a pure
    'does this finding talk about my failure's geometry?' measure):
      * mode-vocabulary overlap: how much the finding's TEXT talks about the geometry
        of the dominant failure mode (precision vs recall vocab);
      * signature overlap: tokens shared with a free-form ``signature`` string built
        from the actual failure report (e.g. dominant feature axes), when provided;
      * a small tag bonus (the old precision/recall tag).
    Higher = more relevant. Never raises; unknown mode falls back to both vocabs.
    """
    text_tokens = _tokenize(f.text or f.title)
    vocab = set()
    if failure_mode in _MODE_VOCAB:
        vocab = set(_MODE_VOCAB[failure_mode])
    else:  # cold_start / both / unknown -> consider both geometries
        for v in _MODE_VOCAB.values():
            vocab |= set(v)
    # Count vocab hits as substrings of the finding text (so multi-word phrases like
    # "false merge" match), normalized by vocab size.
    ftext = (f.text or f.title or "")
    vocab_hits = sum(1 for kw in vocab if kw in ftext)
    vocab_score = vocab_hits / max(1, len(vocab)) * 4.0   # weight up (dominant signal)

    sig_score = 0.0
    if signature:
        sig_tokens = _tokenize(signature)
        if sig_tokens:
            overlap = len(text_tokens & sig_tokens)
            sig_score = overlap / max(1, len(sig_tokens)) * 3.0

    want = {"precision": {"precision"}, "recall": {"recall"}}.get(
        failure_mode, {"precision", "recall"})
    tag_bonus = 0.5 if (f.tags & want) else 0.0
    return vocab_score + sig_score + tag_bonus


def ranking_score(f: "Finding", failure_mode: str, signature=None,
                  failed_findings=None, shown_counts=None) -> float:
    """Menu-ordering score = importance-weighted relevance, minus feedback nudges.

    This is the WEIGHTED SUM that decides the order the agent sees findings in:
      + relevance(...)                        — content match to this failure
      + PRIORITY_WEIGHT * priority            — discovery importance (a REAL co-driver
                                                now, not the old 0.1 tie-breaker)
      - 2.0 if cited in a REVERTED gen        — tried-and-failed against this lineage
      - 0.5 * times already surfaced          — rotation, so repeats fade

    The two feedback terms are soft ORDER nudges (they push a finding DOWN the menu),
    never hard filters: nothing qualifying is hidden, so the agent can still choose a
    down-weighted lever if it judges it fits. Deterministic (no RNG).
    """
    failed = set(failed_findings or ())
    shown = dict(shown_counts or {})
    score = relevance(f, failure_mode, signature)
    score += PRIORITY_WEIGHT * min(max(f.priority, 0.0), 1.0)
    if f.num in failed:
        score -= 2.0
    score -= 0.5 * shown.get(f.num, 0)
    return score


def load_findings(priors_path: str) -> list:
    """Parse the knowledge base into ``Finding`` objects. Returns [] on any problem
    (missing/garbled file) so the caller can proceed without a priors section."""
    try:
        with open(priors_path) as f:
            text = f.read()
    except OSError:
        return []

    findings: list = []
    cur = None          # (num, title, priority)
    body: list = []

    def _flush():
        if cur is None:
            return
        num, title, priority = cur
        blob = "\n".join(body)
        verdict_line = ""
        conclusion = ""
        for ln in body:
            s = ln.strip()
            if s.startswith("- **Verdict carried over:") or s.startswith("**Verdict carried over:"):
                verdict_line = s
            elif (not conclusion) and ("**Conclusion" in s):
                # Text after the 'Conclusion' marker; strip the markdown '**' and any
                # leading colon/space so the snippet starts at the real sentence.
                after = s.split("Conclusion", 1)[1]
                after = after.split(":", 1)[1] if ":" in after else after
                conclusion = after.lstrip("* )").strip()
        findings.append(Finding(num, title, priority, verdict_line,
                                 conclusion, _tags_for(title),
                                 text=f"{title}. {conclusion}".lower()))

    for line in text.splitlines():
        m = _HEADER_RE.match(line)
        if m:
            _flush()
            num = int(m.group(1))
            meta, title = m.group(2), m.group(3)
            pm = _PRIORITY_RE.search(meta)
            priority = float(pm.group(1)) if pm else 0.0
            cur = (num, title, priority)
            body = []
        elif cur is not None:
            body.append(line)
    _flush()
    return findings


def rank_for_report(findings: list, failure_mode: str, signature=None,
                    failed_findings=None, shown_counts=None) -> list:
    """RANK the WHOLE qualifying set for THIS generation (no top-k truncation).

    Returns every qualifying finding ordered best-first by ``ranking_score`` =
    importance-weighted relevance minus the soft feedback nudges (reverted / rotation).
    The agent then reads this ranked MENU and is free to pick or COMBINE any of them —
    the harness no longer forces a top-2. Deterministic; ties broken by finding number.

    ``failed_findings`` : set[int] of finding numbers cited in a reverted gen.
    ``shown_counts``    : dict[int,int] of how many times each finding was surfaced.
    Both default empty (first generation / feedback disabled) → pure importance×relevance.
    """
    q = [f for f in findings if f.qualifies]
    if not q:
        return []

    def _key(f):
        s = ranking_score(f, failure_mode, signature,
                          failed_findings=failed_findings, shown_counts=shown_counts)
        # Tie-break deterministically by finding number so the order is stable.
        return (s, -f.num)

    q.sort(key=_key, reverse=True)
    return q


def select_for_report(findings: list, failure_mode: str, k: int = 2,
                       signature=None, failed_findings=None, shown_counts=None) -> list:
    """Back-compat shim: the top-``k`` of ``rank_for_report`` (see it for the ranking).

    Kept so any caller still asking for a fixed few keeps working; the report itself
    now inlines the FULL ranked menu via ``build_report_section``.
    """
    ranked = rank_for_report(findings, failure_mode, signature=signature,
                             failed_findings=failed_findings, shown_counts=shown_counts)
    return ranked[:k]


_NUM_RE = re.compile(r"\d")


def _snippet(f: Finding, n: int = 480) -> str:
    """The threshold/discriminator text the reviser can key a rule on.

    A rule needs the OPERATIVE NUMBER (e.g. "6.84 µm threshold", "angle > 45°",
    "radius ratio ~1.0"), and in this KB that number is usually NOT in the first
    sentence — the opener is often setup ("Tested whether …"). So instead of the old
    first-sentence-only cut (which dropped the number), keep the sentences that carry
    a DIGIT (the thresholds/discriminators), always including the first for context,
    up to ``n`` chars. Falls back to the leading text if nothing is numeric.
    """
    c = (f.conclusion or "").strip()
    if not c:
        return ""
    # Split into sentences on ". " (keep it simple; the KB is prose).
    import re as _re
    sents = [s.strip() for s in _re.split(r"(?<=[.;])\s+", c) if s.strip()]
    if not sents:
        return c[:n]
    kept, seen = [], set()
    # Always include the first sentence (context), then every number-bearing one.
    for i, s in enumerate(sents):
        if i == 0 or _NUM_RE.search(s):
            if s not in seen:
                kept.append(s); seen.add(s)
        if sum(len(x) + 1 for x in kept) >= n:
            break
    out = " ".join(kept).strip()
    return out[:n] if len(out) > n else out


# How many top-ranked findings get the FULL threshold/discriminator write-up. The
# rest are still listed (title + priority + one-line snippet) as a compact menu, so
# the agent knows every available lever without the section ballooning. This is a
# DISPLAY detail only — nothing is hidden or filtered, the whole qualifying set is
# shown; ``top_detail`` just controls how verbose each entry is.
_TOP_DETAIL = 4


def render_section(ranked: list, failure_mode: str, top_detail: int = _TOP_DETAIL,
                   failed_findings=None, shown_counts=None) -> list:
    """Render the inlined 'grounding priors' MENU as a list of markdown lines.

    ``ranked`` is the WHOLE qualifying set, best-first (see ``rank_for_report``).
    Returns [] when nothing qualified. The block is written ONCE at the top of the
    failure report (a cross-brain generality, not per-brain). The agent is told these
    are ranked by discovery importance × relevance and that it is FREE to read, pick,
    or COMBINE any of them — the harness no longer forces a top-2.
    """
    if not ranked:
        return []
    failed = set(failed_findings or ())
    shown = dict(shown_counts or {})
    mode_h = {"precision": "OVER-MERGING (you created false merges — tighten)",
              "recall": "UNDER-REPAIR (correct merges, but splits left unrepaired — "
                        "raise recall)",
              "cold_start": "COLD START (policy is not merging yet — start repairing "
                            "the safest splits)"}.get(failure_mode,
                            "MIXED (precision and recall both in play)")
    which = ("the SplitSite audit's 'WRONGLY accepted false joins' bucket"
             if failure_mode == "precision"
             else "the SplitSite audit's 'MISSED real splits' bucket")
    lines = [
        "\n## Grounding priors (validated cross-brain — ranked for THIS failure mode)\n",
        f"Dominant failure mode this generation: **{mode_h}**. Every finding below is "
        f"from the AutoDiscovery knowledge base and is pre-filtered to those that "
        f"GENERALIZE across every brain AND survive statistical correction. They are "
        f"GT-derived POPULATION geometry (not this run's labels), so keying a "
        f"threshold/discriminator on them is fair game and does NOT violate the "
        f"no-hardcoded-label rule. They only BIAS your proposal — the held-out gate "
        f"still decides.\n",
        f"**How to use this menu:** it is ranked by **discovery importance (Priority, "
        f"0–1) × relevance to your current failure**. Priority reflects how important / "
        f"high-payoff a finding was across discovery runs — when two levers fit your "
        f"failure comparably, prefer the higher-Priority one. You are FREE to read, "
        f"pick, or COMBINE any findings here (not just the top one); a `↓` marks a "
        f"lever already tried-and-reverted or shown many times — usable, but prefer a "
        f"fresh one. Cite the finding number(s) you rely on in your rules.md change "
        f"log (e.g. 'Finding #8') so we can measure whether grounding helps.\n",
    ]

    def _flag(f):
        marks = []
        if f.num in failed:
            marks.append("tried-and-reverted")
        if shown.get(f.num, 0) > 0:
            marks.append(f"shown×{shown[f.num]}")
        return f"  ↓ ({'; '.join(marks)})" if marks else ""

    # Top tier: full threshold/discriminator write-up.
    lines.append("\n**Top-ranked levers (full detail):**\n")
    for f in ranked[:top_detail]:
        lines.append(
            f"- **Finding #{f.num} — {f.title}** (Priority {f.priority:.2f}){_flag(f)}\n"
            f"  - Threshold/discriminator: {_snippet(f)}\n"
            f"  - Use it against: {which}.\n"
        )
    # Remaining qualifying levers: compact one-liners so the agent still sees them all.
    rest = ranked[top_detail:]
    if rest:
        lines.append("\n**Other qualifying levers (same trust bar, lower rank — "
                     "title · Priority · one-line discriminator):**\n")
        for f in rest:
            snip = _snippet(f, n=140)
            lines.append(
                f"- #{f.num} (P{f.priority:.2f}) — {f.title}{_flag(f)}"
                + (f" — {snip}" if snip else "") + "\n"
            )
    return lines


def build_report_section(priors_path: str, failure_mode: str, top_detail: int = _TOP_DETAIL,
                         signature=None, failed_findings=None, shown_counts=None):
    """Convenience: load + rank + render the full MENU in one call.

    Returns ``(lines, shown_nums)`` where ``lines`` is the markdown block (``[]`` on
    any failure, so the report builder can splice unconditionally). The whole
    qualifying set is inlined, ranked by importance × relevance; the top ``top_detail``
    get a full write-up, the rest a compact one-liner.

    ``shown_nums`` is the TOP-TIER finding numbers (the prominently featured ones) —
    the caller folds these into ``shown_counts`` so the rotation nudge cycles WHICH
    levers get top billing over generations (the full menu is always visible; rotation
    only reorders the spotlight). The extra args thread the CLOSED feedback loop
    (signature = content match; failed_findings = down-weight tried-and-reverted;
    shown_counts = rotation)."""
    try:
        findings = load_findings(priors_path)
        ranked = rank_for_report(findings, failure_mode, signature=signature,
                                 failed_findings=failed_findings,
                                 shown_counts=shown_counts)
        lines = render_section(ranked, failure_mode, top_detail=top_detail,
                               failed_findings=failed_findings, shown_counts=shown_counts)
        return lines, [f.num for f in ranked[:top_detail]]
    except Exception:
        return [], []


# A rules.md change-log citation of a finding, e.g. "Finding #8", "finding 8",
# "#8". We require the explicit '#'/'finding' form so a bare number in prose (a µm
# threshold, a count) is not a citation. We deliberately do NOT match a bare "F8"/
# "F1": "F1" collides with the F1-score wording that appears in the priors text
# itself (finding #1's "F1 = 0.9945"), which would be a false positive if echoed.
_CITE_RE = re.compile(r"(?:finding\s*#?\s*|#)(\d{1,3})\b", re.IGNORECASE)


def cited_findings(change_log_text: str) -> set:
    """Return the set of finding numbers the reviser cited in text it wrote.

    Layer-2 'grounded' detection: the prompt already asks the reviser to cite the
    finding number(s) it relied on in the rules.md change log. A citation means the
    prior MAY have shaped the edit — but citing is not the same as USING (see
    ``supported_citations`` for the stronger check). Used to tag the generation
    grounded vs exploratory so we can measure whether grounding generalizes better.
    """
    if not change_log_text:
        return set()
    return {int(m.group(1)) for m in _CITE_RE.finditer(change_log_text)}


# Domain stop-words: tokens too generic to prove a finding was actually USED (they
# appear in almost every finding + almost every rule change). A citation is only
# "supported" if the added text shares CONTENTFUL vocabulary with the finding beyond
# these — so "I applied finding #1" with no matching geometry term is NOT supported.
_GENERIC_TOKENS = frozenset((
    "the", "and", "for", "with", "this", "that", "split", "merge", "merges", "splits",
    "neuron", "neurons", "fragment", "fragments", "gap", "edit", "edits", "policy",
    "rule", "rules", "finding", "change", "threshold", "add", "added", "use", "using",
))


def supported_citations(change_log_text: str, added_code_text: str,
                        findings: list) -> set:
    """Subset of cited findings whose CONTENT actually shows up in what the reviser
    changed — a stronger 'grounded' signal than a bare ``#N`` citation.

    A citation of finding N is SUPPORTED when the reviser's added text (rules change
    log + the added heuristics.py lines) shares at least one CONTENTFUL token with
    finding N's own text (title + conclusion), excluding generic domain stop-words.
    This distinguishes "cited AND the edit reflects the finding's geometry" from
    "typed #N but changed something unrelated" — closing the gap the reviewer flagged
    (citing ≠ using). Conservative by construction: it can miss a genuine use that
    shares no vocabulary, so it is reported ALONGSIDE the raw citation, not instead of
    it (the harness records both; the payoff analysis can use the stronger one).
    """
    cited = cited_findings(change_log_text)
    if not cited or not findings:
        return set()
    by_num = {f.num: f for f in findings}
    added_tokens = _tokenize(f"{change_log_text}\n{added_code_text or ''}") - _GENERIC_TOKENS
    supported = set()
    for n in cited:
        f = by_num.get(n)
        if f is None:
            continue
        ftoks = (_tokenize(f.text or f.title) - _GENERIC_TOKENS)
        if added_tokens & ftoks:
            supported.add(n)
    return supported
