"""
Discovery-priors index: parse the validated cross-run knowledge base and select
the FEW findings relevant to a generation's dominant failure mode, so they can be
INLINED into the failure report (Layer 1 of the priors overhaul).

Why inline instead of "go read the file":
  The old flow only POINTED the reviser at ``all-runs.combined.md`` and hoped it
  opened it (``read_priors`` was often False -> "un-grounded improvement"). Making
  the grounding a section of the report the reviser already reads removes the
  "didn't read" failure mode entirely, and matching to THIS generation's failure
  mode keeps the signal focused instead of "survey all 24 findings yourself".

Trust discipline (mirrors ``run_evolution._format_priors``): a finding QUALIFIES
only if its Generalization is GENERALIZES and its verdict is NOT in the distrust
set (DOES-NOT-GENERALIZE / PARTIAL / WEAKENED / OVERTURNED). These are GT-derived
POPULATION statistics about error geometry, never this run's labels, so using
their thresholds/discriminators does not violate the no-hardcoded-label rule.

The parser is deliberately tolerant: the knowledge base is regenerated by the
AutoDiscovery consolidation workflow, so we key on the stable structure (``### N.
(Priority …) title`` headers + a ``**Verdict carried over:**`` line) and degrade to
"no priors section" rather than ever raising into the evolution loop.
"""

from __future__ import annotations

import re


# A finding is DISTRUSTED (never inlined) if its verdict line carries any of these
# — the same list run_evolution._format_priors tells the reviser to avoid.
_DISTRUST = ("DOES-NOT-GENERALIZE", "PARTIAL", "WEAKENED", "OVERTURNED")

_HEADER_RE = re.compile(r"^###\s+(\d+)\.\s*\(([^)]*)\)\s*(.+?)\s*$")
_PRIORITY_RE = re.compile(r"Priority\s+([0-9.]+)")

# Keyword sets that tag a finding by which failure mode it informs. A finding may
# carry BOTH (e.g. a proximity classifier bounds recall AND precision). Matched
# against the finding title (lowercased) — robust to the file being renumbered.
_PRECISION_KW = (
    "angle", "angular", "collinear", "colinear", "anti-parallel", "cosine",
    "inertia", "continuation", "crossing", "radius", "caliber", "tortuosity",
    "asymmetric", "overlap", "runaway", "giant",
)
_RECALL_KW = (
    "threshold", "proximity", "gap", "reconnect", "search radius", "bimodal",
    "distance", "branch point", "branch", "distal", "terminal", "micro-fragment",
    "tiny", "small",
)


class Finding:
    """One parsed knowledge-base finding (see module docstring for the fields)."""

    __slots__ = ("num", "title", "priority", "verdict_line", "conclusion", "tags")

    def __init__(self, num, title, priority, verdict_line, conclusion, tags):
        self.num = num
        self.title = title
        self.priority = priority
        self.verdict_line = verdict_line
        self.conclusion = conclusion
        self.tags = tags

    @property
    def qualifies(self) -> bool:
        """GENERALIZES and not in the distrust set (see module docstring)."""
        vl = self.verdict_line or ""
        if "GENERALIZES" not in vl:            # note: 'DOES-NOT-GENERALIZE' lacks the S
            return False
        return not any(bad in vl for bad in _DISTRUST)


def _tags_for(title: str) -> set:
    t = title.lower()
    tags = set()
    if any(k in t for k in _PRECISION_KW):
        tags.add("precision")
    if any(k in t for k in _RECALL_KW):
        tags.add("recall")
    return tags


def load_findings(priors_path: str) -> list:
    """Parse the knowledge base into ``Finding`` objects. Returns [] on any problem
    (missing/garbled file) so the caller can proceed without a priors section."""
    try:
        with open(priors_path) as f:
            text = f.read()
    except OSError:
        return []

    findings: list = []
    cur = None          # (num, title, priority)
    body: list = []

    def _flush():
        if cur is None:
            return
        num, title, priority = cur
        blob = "\n".join(body)
        verdict_line = ""
        conclusion = ""
        for ln in body:
            s = ln.strip()
            if s.startswith("- **Verdict carried over:") or s.startswith("**Verdict carried over:"):
                verdict_line = s
            elif (not conclusion) and ("**Conclusion" in s):
                # Text after the 'Conclusion' marker; strip the markdown '**' and any
                # leading colon/space so the snippet starts at the real sentence.
                after = s.split("Conclusion", 1)[1]
                after = after.split(":", 1)[1] if ":" in after else after
                conclusion = after.lstrip("* )").strip()
        findings.append(Finding(num, title, priority, verdict_line,
                                 conclusion, _tags_for(title)))

    for line in text.splitlines():
        m = _HEADER_RE.match(line)
        if m:
            _flush()
            num = int(m.group(1))
            meta, title = m.group(2), m.group(3)
            pm = _PRIORITY_RE.search(meta)
            priority = float(pm.group(1)) if pm else 0.0
            cur = (num, title, priority)
            body = []
        elif cur is not None:
            body.append(line)
    _flush()
    return findings


def select_for_report(findings: list, failure_mode: str, k: int = 2) -> list:
    """Pick up to ``k`` QUALIFYING findings most relevant to ``failure_mode``.

    ``failure_mode`` is one of ``precision`` (policy is creating false merges —
    over-merging), ``recall`` (correct merges but splits likely left unrepaired),
    or ``cold_start``/``both`` (mix). We rank qualifying findings by whether they
    carry the matching tag, then by the finding's own Priority. Findings tagged for
    BOTH modes (e.g. a proximity classifier) sort high under either mode, which is
    intended — they are foundational to the merge_labels lever.
    """
    q = [f for f in findings if f.qualifies]
    if not q:
        return []
    want = {"precision": {"precision"}, "recall": {"recall"}}.get(
        failure_mode, {"precision", "recall"})

    def _key(f):
        match = 1 if (f.tags & want) else 0
        return (match, f.priority)

    q.sort(key=_key, reverse=True)
    return q[:k]


def _snippet(f: Finding, n: int = 200) -> str:
    """The threshold/discriminator line the reviser can key a rule on."""
    c = f.conclusion or ""
    # First sentence (or a hard cap) — enough to carry the headline number.
    dot = c.find(". ")
    s = c[: dot + 1] if 0 < dot < n else c[:n]
    return s.strip()


def render_section(selected: list, failure_mode: str) -> list:
    """Render the inlined 'grounding priors' block as a list of markdown lines.

    Returns [] when nothing qualified/matched. The block is written ONCE at the top
    of the failure report (it is a cross-brain generality, not per-brain), and each
    finding names WHICH report section it informs so the reviser can act on it in
    place instead of hunting through the full knowledge base.
    """
    if not selected:
        return []
    mode_h = {"precision": "OVER-MERGING (you created false merges — tighten)",
              "recall": "UNDER-REPAIR (correct merges, but splits left unrepaired — "
                        "raise recall)",
              "cold_start": "COLD START (policy is not merging yet — start repairing "
                            "the safest splits)"}.get(failure_mode,
                            "MIXED (precision and recall both in play)")
    lines = [
        "\n## Grounding priors (validated cross-brain — matched to THIS failure mode)\n",
        f"Dominant failure mode this generation: **{mode_h}**. The findings below are "
        f"from the AutoDiscovery knowledge base and are pre-filtered to those that "
        f"GENERALIZE across every brain AND survive statistical correction, then "
        f"matched to that mode. They are GT-derived POPULATION geometry (not this "
        f"run's labels), so keying a threshold/discriminator on them is fair game and "
        f"does NOT violate the no-hardcoded-label rule. They only BIAS your proposal — "
        f"the held-out gate still decides. Cite the finding number in your rules.md "
        f"change log so we can measure whether grounding helps.\n",
    ]
    for f in selected:
        which = ("the SplitSite audit's 'WRONGLY accepted false joins' bucket"
                 if failure_mode == "precision"
                 else "the SplitSite audit's 'MISSED real splits' bucket")
        lines.append(
            f"- **Finding #{f.num} — {f.title}**\n"
            f"  - Threshold/discriminator: {_snippet(f)}\n"
            f"  - Use it against: {which}.\n"
        )
    lines.append(
        "\nThese are the MATCHED few; the full knowledge base has more levers if none "
        "of the above fits — prefer a lever you and prior generations have not tried "
        "yet.\n"
    )
    return lines


def build_report_section(priors_path: str, failure_mode: str, k: int = 2) -> list:
    """Convenience: load + select + render in one call. [] on any failure so the
    report builder can splice the result unconditionally."""
    try:
        findings = load_findings(priors_path)
        return render_section(select_for_report(findings, failure_mode, k), failure_mode)
    except Exception:
        return []


# A rules.md change-log citation of a finding, e.g. "Finding #8", "finding 8",
# "#8". We require the explicit '#'/'finding' form so a bare number in prose (a µm
# threshold, a count) is not a citation. We deliberately do NOT match a bare "F8"/
# "F1": "F1" collides with the F1-score wording that appears in the priors text
# itself (finding #1's "F1 = 0.9945"), which would be a false positive if echoed.
_CITE_RE = re.compile(r"(?:finding\s*#?\s*|#)(\d{1,3})\b", re.IGNORECASE)


def cited_findings(change_log_text: str) -> set:
    """Return the set of finding numbers the reviser cited in text it wrote.

    Layer-2 'grounded' detection: the prompt already asks the reviser to cite the
    finding number(s) it relied on in the rules.md change log. A citation means the
    prior actually SHAPED the edit — strictly stronger than ``read_priors`` (which
    only proves the file was opened). Used to tag the generation grounded vs
    exploratory so we can measure whether grounding generalizes better.
    """
    if not change_log_text:
        return set()
    return {int(m.group(1)) for m in _CITE_RE.finditer(change_log_text)}
