"""Harness-owned dispatch: revisions can replace exactly one scoring component."""

import ast


def compose(sources):
    return ('# Generated by the harness; each component is evaluated separately.\n'
            f'_COMPONENT_SOURCES = {dict(sorted(sources.items()))!r}\n'
            '_COMPONENTS = {}\n'
            'for _kind, _source in _COMPONENT_SOURCES.items():\n'
            '    _namespace = {}\n'
            '    exec(compile(_source, "<component>", "exec"), _namespace)\n'
            '    _COMPONENTS[_kind] = _namespace["score_candidates"]\n'
            'def score_candidates(features, ctx):\n'
            '    return _COMPONENTS[ctx["kind"]](features, ctx)\n')


def components(source):
    tree = ast.parse(source)
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == '_COMPONENT_SOURCES'
                                                for t in node.targets):
            values = ast.literal_eval(node.value)
            if (not isinstance(values, dict) or set(values) != {'merge', 'split'}
                    or not all(isinstance(v, str) for v in values.values()) or compose(values) != source):
                raise ValueError('Invalid harness component bundle')
            return values
    return {'merge': source, 'split': source}
